Repository thingaha/thingaha-web, pull requests merged in 2021-10, with the labels that each got.

#163 Fix user password change functionality being broken
  frontend/src/components/settings/PasswordChangeForm.js
  frontend/src/components/settings/Setting.js
  frontend/src/components/settings/UserPasswordForm.js
  frontend/src/store/actions/settings.js
  frontend/src/store/api/settings.js
  frontend/src/store/api/users.js
  frontend/src/store/reducers/users.js
  frontend/src/store/saga.js
  frontend/src/store/sagas/settings.js
Labels: hacktoberfest, hacktoberfest-accepted, Ready for review

#166 Issue #159 attendance bug
  frontend/src/components/attendances/AttendanceCard.js
  frontend/src/components/attendances/Attendances.js
Labels: hacktoberfest-accepted

#165 #164 update db_schema and add stop_app.sh
  Readme.md
  backend/bin/stop_app.sh
Labels: hacktoberfest-accepted

#167 #146 users can edit their details
  backend/src/common/error.py
  backend/src/controller/api.py
  backend/src/controller/user.py
Labels: hacktoberfest-accepted

#187 Issue 181 remove draft server
  Readme.md
  draft_server/Readme.md
  draft_server/index.js
  draft_server/package.json
  draft_server/sample_data/addresses.json
  draft_server/sample_data/attendances.json
  draft_server/sample_data/donations.json
  draft_server/sample_data/extrafunds.json
  draft_server/sample_data/schools.json
  draft_server/sample_data/studentdonator.json
  draft_server/sample_data/students.json
  draft_server/sample_data/transfer.json
  draft_server/sample_data/users.json
  draft_server/yarn.lock
  frontend/.env.example
  frontend/src/config.js
  frontend/src/store/api/authentication.js
  frontend/src/utils/thingahaApiClient.js
  frontend/src/utils/thingahaFileUploadApiClient.js
Labels: hacktoberfest, hacktoberfest-accepted

#190 Add search by grade, year and student name support to attendances
  backend/docs/attendance.md
  backend/src/controller/attendance.py
  backend/src/models/attendance.py
  backend/src/service/attendance/attendance_service.py
Labels: backend, python, hacktoberfest-accepted

#191 Integrate student search functionality with backend. Implements #177
  frontend/src/components/students/Students.js
  frontend/src/store/actions/students.js
  frontend/src/store/api/students.js
  frontend/src/store/saga.js
  frontend/src/store/sagas/students.js
Labels: frontend, react, hacktoberfest-accepted, Ready for review
